# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1232, 839)
        self.background = QtWidgets.QLabel(Dialog)
        self.background.setGeometry(QtCore.QRect(0, 0, 1311, 881))
        self.background.setStyleSheet("background-color:#0c0c1d;\n"
"")
        self.background.setText("")
        self.background.setObjectName("background")
        self.gif = QtWidgets.QLabel(Dialog)
        self.gif.setGeometry(QtCore.QRect(210, 120, 801, 601))
        self.gif.setStyleSheet("border:none;")
        self.gif.setText("")
        self.gif.setPixmap(QtGui.QPixmap("voice_gif.gif"))
        self.gif.setObjectName("gif")
        self.pushButton1 = QtWidgets.QPushButton(Dialog)
        self.pushButton1.setGeometry(QtCore.QRect(490, 290, 241, 351))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton1.setFont(font)
        self.pushButton1.setStyleSheet("background-color:none;\n"
"border:none;\n"
"")
        self.pushButton1.setText("")
        self.pushButton1.setObjectName("pushButton1")
        self.SPEAK = QtWidgets.QLabel(Dialog)
        self.SPEAK.setGeometry(QtCore.QRect(560, 560, 101, 51))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(20)
        self.SPEAK.setFont(font)
        self.SPEAK.setStyleSheet("color:#8bf4f9;")
        self.SPEAK.setObjectName("SPEAK")
        self.Quit = QtWidgets.QPushButton(Dialog)
        self.Quit.setGeometry(QtCore.QRect(1090, 720, 93, 71))
        self.Quit.setStyleSheet("background-color:transparent;\n"
"")
        self.Quit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("F:\\python\\power.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Quit.setIcon(icon)
        self.Quit.setIconSize(QtCore.QSize(60, 60))
        self.Quit.setObjectName("Quit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(1100, 790, 91, 31))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#8bf4f9;")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.SPEAK.setText(_translate("Dialog", "SPEAK"))
        self.label.setText(_translate("Dialog", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
